### ISSUE TITLE
definição do processo

### ISSUE THREAD

**Issue by alescrocaro** [alescrocaro/jabref#1]
DEFINIÇÃO DO PROCESSO:

**SCRUM:**\
Consiste em uma etapa de planejamento, e várias iterações para desenvolver as funcionalidades informadas nos requisitos do projeto. Ao final de cada iteração (sprint) deve-se ter um produto final.\
Como esse processo é para ser executado em sala, cada sprint foi planejada para durar 300 minutos. Por fim, para saber o quanto a equipe consegue desenvolver em uma sprint, é feito um controle de quantos pontos de complexidade uma equipe produziu em um tempo determinado, porém na primeira sprint não há como se prever, ficando por conta da experiência dos membros.

**Horários disponíveis:**\
17/11/2022: 13:50 às 15:30 > Definição do Processo
21/11/2022: 13:50 às 15:30 > Planejamento (Coleta de Requisitos)
24/11/2022: 13:50 às 15:30 > Planejamento (Planning Poker do Backlog do Projeto)
28/11/2022: 13:50 às 15:30 > Sprint (c/ Reunião de Início)
01/12/2022: 13:50 às 15:30 > Sprint (Desenvolvimento)
05/12/2022: 13:50 às 15:30 > Sprint (c/ Reunião de Finalização)
XX/12/2022: Individual: 300 minutos livres para repor tarefas atrasadas.

## **1. Planejamento**
- **Definição de Papeis**:
  - Aqui a equipe irá definir quem será o Scrum Master, o Product Owner, e os desenvolvedores.

- **Definição de Tarefas**:
  - Aqui será definido o que deverá ser feito, seja por meio de Issues como no caso deste trabalho, ou por meio de histórias de usuário em caso de um projeto à ser realizado do zero.

- **Avaliação Inicial de Complexidade**:
  - Aqui será avaliado a complexidade de cada história de usuário (ou Issue) utilizando o Planning Poker.
	
- **Ordenação das tarefas por relevância**:
  - As primeiras tarefas executadas devem ser as mais importantes, aqui é feita a organização para que nas sprints seja possível visualizar este critério.
	
- **Configuração de Ambiente**:
  - Aqui o projeto será iniciado de forma em que todos os membros consigam desenvolver, compilar e testar o projeto. Isso inclui instalação e configuração de todas as dependências necessárias.

## **2. Sprint**
- **Planejamento da sprint**
  - **Escolher as tarefas**:
    - Aqui será escolhido quais tarefas devem ser executadas na sprint, a escolha deve ser a tarefa de maior relevância que está dentro da capacidade de produção da equipe. 
		
  - **Dividir tarefas e atribuí-las**:
    - Aqui é feito a divisão de tarefas complexas e distribuido aos membros da equipe (exemplo: backend e frontend)

- **Desenvolvimento**
	
- **Qualidade**:
  - Aqui é realizado testes de qualidade, sendo testes de unidade para códigos de lógica, ou testes de visualização manual para códigos de GUI.
	
- **Reunião final da sprint**:
  - **Reavaliar complexidade das tarefas executadas na sprint**
		
  - **Atualizar a capacidade de produção da equipe**:
     - Aqui calculamos a média da complexidade atualizada das ultimas 5 tarefas executadas e somamos com algum valor definido pela equipe (>= 0) para definir quantos pontos de complexidade a equipe consegue desenvolver por sprint.
		
  - **Atualização da Planning Poker da Backlog:**
    - Com um pouco mais de experiência no projeto, equipe refaz a avaliação de complexidade das 5 próximas tarefas da backlog (em ordem de relevância) afim de ajustar para uma melhor atribuição de Issues na próxima sprint.
		
## **3. Finalização**
- **Deploy do projeto**

**Comment by alescrocaro** [comment]
Possiveis issues:
https://github.com/JabRef/jabref/issues/8742

https://github.com/JabRef/jabref/issues/4691

https://github.com/JabRef/jabref/issues/9108

https://github.com/JabRef/jabref/issues/8797

https://github.com/JabRef/jabref/issues/9339

https://github.com/JabRef/jabref/issues/9362

https://github.com/JabRef/jabref/issues/9369

**Comment by caiomiglioli** [comment]
Definição de Papéis

> Possiveis issues: [JabRef#8742](https://github.com/JabRef/jabref/issues/8742)
> 
> [JabRef#4691](https://github.com/JabRef/jabref/issues/4691)
> 
> [JabRef#9108](https://github.com/JabRef/jabref/issues/9108)
> 
> [JabRef#8797](https://github.com/JabRef/jabref/issues/8797)
> 
> [JabRef#9339](https://github.com/JabRef/jabref/issues/9339)
> 
> [JabRef#9362](https://github.com/JabRef/jabref/issues/9362)
> 
> [JabRef#9369](https://github.com/JabRef/jabref/issues/9369)

por mim ta filé, dá pra usar esses mesmos
