### ISSUE TITLE
 Groups only show 4 digit number of entries

### ISSUE THREAD

**Issue by JVZavatin** [alescrocaro/jabref#5]
JabRef version

Other (please describe below)
Operating system

GNU / Linux
Details on version and operating system

JabRef 5.7--2022-05-15--a90ee23 Linux 5.17.6-300.fc36.x86_64 amd64 Java 18.0.1 JavaFX 18+12
Checked with the latest development build

I made a backup of my libraries before testing the latest development version.

    I have tested the latest development version and the problem persists

Steps to reproduce the behaviour

open a library with more than 9999 entries; the first digit is not shown on my system.
Appendix

![](https://user-images.githubusercontent.com/20518297/168476574-e2c8c274-c438-439c-bc26-72856f68306f.png)

 link original: https://github.com/JabRef/jabref/issues/8797

**Comment by alescrocaro** [comment]
solved by https://github.com/JabRef/jabref/commit/4c62e287811d9b88b957e2bb0e4ffb48eb9a0d79
